[package]
name = "mqi"
description = "Idiomatic IBM® MQ Interface (MQI) and MQ Administration Interface (MQAI) APIs"
repository = "https://github.com/advantic-au/mqi"
version = "0.1.0"
authors = ["Warren Spits <warren@advantic.au>"]
license = "Apache-2.0"
keywords = ["message-queue", "messaging"]
categories = ["asynchronous"]

rust-version = "1.81"
edition = "2021"
build = "build/mod.rs"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[features]
default = [
    "link",
    "constantgen",
    "runnable",
    "mqmgen",
    "mqc_9_2_0_0",
]

docsrs = ["libmqm-sys/docsrs", "mqai", "link", "dlopen2", "mqc_9_4_1_0"]

## Minimal features to make the code runnable
runnable = [
    "libmqm-sys/mqi_helpers",
]

## Generate the constants (default is to use pregenerated constants)
constantgen = [
    "runnable",
]

## Generate the constants and save them in the src folder
pregen = [
    "constantgen",
    "mqai",
    "mqc_9_4_1_0",
]

## Enable tracing in the MQI calls
tracing = ["dep:tracing"]
## Enable the administrative API
mqai = ["libmqm-sys/mqai"]
## Link the MQI library at compile time
link = ["libmqm-sys/link"]
## Enable runtime loading of the MQI library using [`dlopen2`](dlopen2)
dlopen2 = ["libmqm-sys/dlopen2"]
## Generate the MQI bindings and defaults
mqmgen = ["libmqm-sys/bindgen", "libmqm-default/defaultgen"]
## MQI and MQAI function mocking for unit and integration tests
mock = ["dep:mockall"]

## Minimum MQ client version 9.2.0.0
mqc_9_2_0_0 = ["libmqm-sys/mqc_9_2_0_0"]
## Minimum MQ client version 9.3.0.0
mqc_9_3_0_0 = [
    "libmqm-sys/mqc_9_3_0_0",
    "libmqm-default/mqc_9_3_0_0",
    "mqc_9_2_0_0",
]
## Minimum MQ client version 9.3.1.0
mqc_9_3_1_0 = [
    "libmqm-sys/mqc_9_3_1_0",
    "libmqm-default/mqc_9_3_1_0",
    "mqc_9_3_0_0",
]
## Minimum MQ client version 9.3.2.0
mqc_9_3_2_0 = [
    "libmqm-sys/mqc_9_3_2_0",
    "mqc_9_3_1_0",
]
## Minimum MQ client version 9.3.4.0
mqc_9_3_4_0 = [
    "libmqm-sys/mqc_9_3_4_0",
    "mqc_9_3_2_0",
]
## Minimum MQ client version 9.4.1.0
mqc_9_4_1_0 = [
    "libmqm-sys/mqc_9_4_1_0",
    "mqc_9_3_4_0",
]

[dependencies]
phf = { default-features = false, version = "0.11.2" }
page_size = "0.6.0"
libmqm-sys = { version = "0.6.0", default-features = false }
libmqm-default = { version = "0.6.0", default-features = false }
tracing = { version = "0.1.40", optional = true }
dlopen2 = "0.7.0"
regex-lite = "0.1.6"
derive_more = { version = "1.0.0", features = [
    "deref",
    "deref_mut",
    "as_ref",
    "from",
    "error",
    "display",
    "constructor",
    "add",
    "add_assign",
] }
maybe-owned = "0.3.4"
mockall = { version = "0.13.0", optional = true }
document-features = "0.2.10"

[build-dependencies]
libmqm-sys = { version = "0.6.0", default-features = false }
phf = { default-features = false, version = "0.11" }
phf_codegen = "0.11.2"

[lints.rust]
unsafe_op_in_unsafe_fn = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }

[lints.clippy]
all = { level = "deny", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
allow_attributes = "warn"

# TODO - These should be removed and the underlying problem fixed
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"

[package.metadata.docs.rs]
features = ["docsrs"]
no-default-features = true

[dev-dependencies]
# Mocking
mockall = "0.13.0"

# development dependencies for examples
clap = { version = "4.5.16", features = ["derive"] }
anyhow = "1.0.87"
tracing = "0.1.40"
tracing-subscriber = "0.3"
ctrlc = "3.4"

[[example]]
name = "subscribe_managed"
required-features = ["link", "runnable"]

[[example]]
name = "readme"
required-features = ["link", "runnable"]

[[example]]
name = "open_put"
required-features = ["link", "runnable"]

[[example]]
name = "forward"
required-features = ["link", "runnable"]
