[package]
name = "mqi"
description = "Idiomatic IBM® MQ Interface (MQI) and MQ Administration Interface (MQAI) APIs"
repository = "https://github.com/advantic-au/mqi"
version = "0.1.0"
authors = ["Warren Spits <warren@advantic.au>"]
license = "Apache-2.0"
keywords = ["message-queue", "messaging"]
categories = ["asynchronous"]

rust-version = "1.87"
edition = "2024"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[features]
default = ["link", "mqc_9_2_0_0"]
docsrs = [
    "libmqm-sys/docsrs",
    "dep:document-features",
    "mqai",
    "exits",
    "link",
    "dlopen2",
    "mqc_9_4_2_0",
]
## Enable tracing in the MQI calls
tracing = ["dep:tracing"]
## Enable the administrative API
mqai = ["libmqm-sys/mqai", "libmqm-constants/mqai"]
## Enable the exits API
exits = ["libmqm-sys/exits", "libmqm-constants/exits"]
## Link the MQI library at compile time
link = ["libmqm-sys/link"]
## Enable runtime loading of the MQI library using [`dlopen2`](dlopen2)
dlopen2 = ["libmqm-sys/dlopen2", "dep:dlopen2"]
## Generate the bindings c bindings, constants and defaults using the provided MQ library
mqm_generate = [
    "libmqm-sys/bindgen",
    "libmqm-default/generate",
    "libmqm-constants/generate",
]
## MQI and MQAI function mocking for unit and integration tests
mock = ["dep:mockall"]

## Minimum MQ client version 9.2.0.0
mqc_9_2_0_0 = ["libmqm-sys/mqc_9_2_0_0", "libmqm-constants/mqc_9_2_0_0"]
## Minimum MQ client version 9.3.0.0
mqc_9_3_0_0 = [
    "libmqm-sys/mqc_9_3_0_0",
    "libmqm-default/mqc_9_3_0_0",
    "libmqm-constants/mqc_9_3_0_0",
    "mqc_9_2_0_0",
]
## Minimum MQ client version 9.3.1.0
mqc_9_3_1_0 = [
    "libmqm-sys/mqc_9_3_1_0",
    "libmqm-default/mqc_9_3_1_0",
    "libmqm-constants/mqc_9_3_1_0",
    "mqc_9_3_0_0",
]
## Minimum MQ client version 9.3.2.0
mqc_9_3_2_0 = [
    "libmqm-sys/mqc_9_3_2_0",
    "libmqm-constants/mqc_9_3_2_0",

    "mqc_9_3_1_0",
]
## Minimum MQ client version 9.3.3.0
mqc_9_3_3_0 = [
    "libmqm-sys/mqc_9_3_3_0",
    "libmqm-constants/mqc_9_3_3_0",
    "mqc_9_3_2_0",
]
## Minimum MQ client version 9.3.4.0
mqc_9_3_4_0 = [
    "libmqm-sys/mqc_9_3_4_0",
    "libmqm-constants/mqc_9_3_4_0",
    "mqc_9_3_3_0",
]
## Minimum MQ client version 9.3.5.0
mqc_9_3_5_0 = [
    "libmqm-sys/mqc_9_3_5_0",
    "libmqm-constants/mqc_9_3_5_0",
    "mqc_9_3_4_0",
]
## Minimum MQ client version 9.4.0.0
mqc_9_4_0_0 = [
    "libmqm-sys/mqc_9_4_0_0",
    "libmqm-constants/mqc_9_4_0_0",
    "mqc_9_3_5_0",
]
## Minimum MQ client version 9.4.1.0
mqc_9_4_1_0 = [
    "libmqm-sys/mqc_9_4_1_0",
    "libmqm-constants/mqc_9_4_1_0",

    "mqc_9_4_0_0",
]
## Minimum MQ client version 9.4.2.0
mqc_9_4_2_0 = [
    "libmqm-sys/mqc_9_4_2_0",
    "libmqm-constants/mqc_9_4_2_0",
    "mqc_9_4_1_0",
]

[dependencies]
regex-lite = "0.1.6"
libmqm-sys = { version = "0.8.0", default-features = false, git = "https://github.com/advantic-au/libmqm-sys", branch = "develop" }
libmqm-default = { version = "0.8.0", default-features = false, git = "https://github.com/advantic-au/libmqm-sys", branch = "develop" }
libmqm-constants = { version = "0.8.0", default-features = false, git = "https://github.com/advantic-au/libmqm-sys", branch = "develop" }
tracing = { version = "0.1.40", optional = true }
dlopen2 = { version = "0.8.0", optional = true }
derive_more = { version = "2.0.1", features = [
    "deref",
    "deref_mut",
    "as_ref",
    "from",
    "error",
    "display",
    "constructor",
] }
maybe-owned = "0.3.4"
mockall = { version = "0.13.0", optional = true }
document-features = { version = "0.2.10", optional = true }

[lints.rust]
unsafe_op_in_unsafe_fn = "warn"
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(coverage,coverage_nightly)',
] }

[lints.clippy]
all = { level = "deny", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
allow_attributes = "warn"

# TODO - These should be removed and the underlying problem fixed
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[package.metadata.docs.rs]
features = ["docsrs"]
no-default-features = true

[dev-dependencies]
# Mocking
mockall = "0.13.0"
proptest = "1.6.0"

# development dependencies for examples
clap = { version = "4.5.16", features = ["derive"] }
anyhow = "1.0.87"
tracing = "0.1.40"
tracing-subscriber = "0.3.19"
ctrlc = "3.4"

[[example]]
name = "subscribe_managed"
required-features = ["link"]

[[example]]
name = "readme"
required-features = ["link"]

[[example]]
name = "open_put"
required-features = ["link"]

[[example]]
name = "forward"
required-features = ["link"]

[[example]]
name = "dlopen"
required-features = ["dlopen2"]
