// Autogenerated code doesn't need checking
#![allow(clippy::all)]
#![allow(clippy::pedantic)]
#![allow(clippy::nursery)]

use super::*;

#[cfg(feature = "constantgen")]
// This file is generated during the build process
include!(concat!(env!("OUT_DIR"), "/mqconstants.rs"));

#[cfg(not(feature = "constantgen"))]
// This file is pregenerated
include!("./pregen/mqconstants.rs");

/// Return codes can sometimes be in the MQRCCF range so combine the two
pub const MQRC_FULL_CONST: ConstSource<PhfSource, PhfSource> = ConstSource(mapping::MQRC_CONST, mapping::MQRCCF_CONST);
