name: Test Coverage
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  test:
    name: "Coverage"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: latest
      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@e6d2212084e8121f2066d3e2108daeded348b9e0 # v2.56.4
        with:
          tool: nextest, cargo-llvm-cov
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - name: Generate code coverage
        run: |
          cargo llvm-cov --no-report nextest --profile ci --features mqai,dlopen2,mqc_9_4_2_0,mock
          cargo llvm-cov --no-report test --doc --features mqai,dlopen2,mqc_9_4_2_0,mock
          cargo llvm-cov report --doctests --ignore-filename-regex "build/.+" --codecov --output-path coverage/codecov.json
          cargo llvm-cov report --doctests --ignore-filename-regex "build/.+"
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
