name: Test Coverage
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "Coverage"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: 9.4.1.0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2
      - name: Generate code coverage
        run: |
          cargo llvm-cov --no-report nextest --profile ci --all-features
          cargo llvm-cov report --codecov --output-path coverage/codecov.json
          cargo llvm-cov report
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
