name: Incremental Mutant Testing
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  incremental_mutants:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: 9.4.1.0
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Relative diff
        run: |
          git branch -av
          git diff origin/${{ github.base_ref }}.. > git.diff
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-mutants
      - name: Mutant testing
        run: |
          cargo mutants --no-shuffle -vV --in-diff git.diff --all-features
      - name: Artefact mutants-incremental.out
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-incremental.out
          path: mutants.out
