name: Full Mutant Testing
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  mutants:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      - uses: taiki-e/install-action@b651345a718c8f44efa2460560b3dbf29cbd7ee1 # v2.75.26
        with:
          tool: cargo-mutants
      - name: Mutant testing
        run: |
          cargo mutants -vV --in-place --all-features
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Artefact mutants.out
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: mutants-out
          path: mutants.out
