name: Full Mutant Testing
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  mutants:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
      - uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - uses: taiki-e/install-action@e6d2212084e8121f2066d3e2108daeded348b9e0 # v2.56.4
        with:
          tool: cargo-mutants
      - name: Mutant testing
        run: |
          cargo mutants -vV --in-place --all-features
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Artefact mutants.out
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-out
          path: mutants.out
