name: Full Mutant Testing
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  mutants:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: advantic-au/action-mq-client@stable
        id: mq-client
        with:
          client-version: latest
      - uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - uses: taiki-e/install-action@914ac1e29db2d22aef69891f032778d9adc3990d # v2.49.34
        with:
          tool: cargo-mutants
      - name: Mutant testing
        run: |
          cargo mutants -vV --in-place --all-features
        env:
          MQ_HOME: ${{ steps.mq-client.outputs.client-install-path }}
      - name: Artefact mutants.out
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-out
          path: mutants.out
